name: Eureco Time Action

on:
  schedule:
    - cron: '0 4 * * 4'

jobs:
  eureco_time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Run Python
        env:
          MEMBERS: ${{ secrets.MEMBERS }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
        run: python group_generator.py
